Add component page template
js-tasks-ru/htmlcss-20230530_aleksbondarev pull request #13
Opened 2023-06-18 14:13 UTC by bondarev

2023-06-18 14:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-18 21:43 UTC, GSemikozov requested changes

2023-06-18 21:43 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title_sm {
.footer_sm .footer__title {}

2023-06-19 05:20 UTC, bondarev commented on components/footer/footer.css
> +.footer__title_sm {
Точно, готово)

2023-06-19 05:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-19 05:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 05:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 05:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 20:36 UTC, GSemikozov approved these changes

2023-06-19 20:36 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-06-19 20:39 UTC, GSemikozov approved these changes

2023-06-19 20:39 UTC, merged