Add avatar component
js-tasks-ru/htmlcss-20230530_aleksbondarev pull request #15
Opened 2023-06-21 18:16 UTC by bondarev

2023-06-21 18:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-22 20:43 UTC, GSemikozov requested changes

2023-06-22 20:43 UTC, GSemikozov commented on 06-lection4/01-avatar/index.html
> +<div class="avatar" style="width: 102px; height: 102px;">
все-таки не надо инлайнить - лучше офрмить через модификаторы (у нас в макете встречается всего 3 варианта размеров)

2023-06-22 21:31 UTC, bondarev commented on 06-lection4/01-avatar/index.html
> +<div class="avatar" style="width: 102px; height: 102px;">
Добавил)

2023-06-22 21:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-23 13:51 UTC, GSemikozov approved these changes

2023-06-23 13:51 UTC, merged