Add module 4 layout (cards)
js-tasks-ru/htmlcss-20230530_aleksbondarev pull request #9
Opened 2023-06-12 18:08 UTC by bondarev

2023-06-12 18:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-12 18:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-12 20:28 UTC, GSemikozov requested changes

2023-06-12 20:28 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__card {
лучше сразу вынесем как отдельный компонент

2023-06-12 21:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-12 21:21 UTC, bondarev commented on components/preview/preview.css
> +.preview__card {
Готово 👍🏻

2023-06-12 21:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-13 09:14 UTC, GSemikozov approved these changes

2023-06-13 09:14 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-06-13 09:16 UTC, GSemikozov approved these changes

2023-06-13 09:16 UTC, merged